spring:
  application:
    name:
      come2us
  profiles:
    active: local
    include:
#?? redis, cloud ?? ??? ? ??

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
